model_name: 'drnetq' # drnetq, inceptionv3, inceptionv4, resnet18, resnet152, vgg13, vgg19, swin_custom, swin_tiny, nat_mini, nat_custom

paths:
  train_imgdir: 'datasets/classification/d1/train'
  val_imgdir: 'datasets/classification/d1/val'
  test_imgdir: 'datasets/classification/d1/test'

hyperparameters:
  loss_fn: 'cross_entropy'
  optimizer: 'adam' # sgd
  batch_size: 40
  num_epochs: 500
  lr: 0.005
  b1: 0.9
  b2: 0.999
  weight_decay: 0.001
  scheduler: 
    type: 'step' # cosine, exponential
    gamma: 0.6
    step: 10
  n_gpus: 2

general:
  pretrain: True
  n_classes: 2
  img_size: 224
