model_name: 'inceptionv4' # drnetq, inceptionv3, inceptionv4, resnet18, resnet152, vgg13, vgg19, swin_custom, swin_tiny, nat_mini, nat_custom

paths:
  train_imgdir: 'datasets/dataset_1/train'
  val_imgdir: 'datasets/dataset_1/val'
  test_imgdir: '/home/alonso/Documents/fundus_suitable/datasets/dataset_1/test'

hyperparameters:
  loss_fn: 'cross_entropy'
  optimizer: 'adam' # sgd
  batch_size: 64
  num_epochs: 500
  lr: 0.0005
  b1: 0.9
  b2: 0.999
  weight_decay: 0.0001
  scheduler: 
    type: 'step' # cosine, exponential
    gamma: 0.9
    step: 50
  n_gpus: 1

general:
  pretrain: False
  n_classes: 5
  img_sizeh: 224
  img_sizew: 224
