# ├── yolov5
#     └── dataset
#         └── train.txt
#         └── val.txt
model_pretrain: src/detection/yolov5n.pt
path: /home/alonso/Documents/fundus_suitable/dataset/detection/retina  # dataset root dir
train: train.txt  # train images (relative to 'path') 960 images
val: val.txt  # val images (relative to 'path') 240 images
test: #
epochs: 50
batch_size: 32
# Classes
nc: 2  # number of classes
names: ['macula', 'OD']  # class names
