model_name: 'swin_unet_custom' #unet, unet_imagenet, swin_unet, swin_unet_custom

unet_encoder: 'resnet18'

swin_unet_custom_architecture:
  embed_dim: 24
  depths: [2, 2, 2, 2]
  num_heads: [2, 2, 2, 2]
  window_size: 7
  drop_path_rate: 0.1

unet_architecutre:
  feature_start: 64
  layers: 4
  bilinear: False
  dropout: 0.0
  kernel_size: 3
  stride: 1
  padding: 1

paths:
  train_imgdir: 'dataset/dataset_roi2/train_images'
  train_mskdir: 'dataset/dataset_roi2/train_masks'
  val_imgdir: 'dataset/dataset_roi2/val_images'
  val_mskdir: 'dataset/dataset_roi2/val_masks'

hyperparameters:
  loss_fn: 'binary_crossentropy'
  optimizer: 'sgd' # sgd
  batch_size: 64
  num_epochs: 50
  lr: 0.001
  b1: 0.9
  b2: 0.999
  weight_decay: 0.0001
  scheduler: 
    type: 'step' # cosine, exponential
    gamma: 0.8
    step: 5
  n_gpus: 1

general:
  pretrain: False
  n_classes: 1
  img_size: 224
