paths:
  train_imgdir: 'dataset/dataset_roi2/train_images'
  train_mskdir: 'dataset/dataset_roi2/train_masks'
  val_imgdir: 'dataset/dataset_roi2/val_images'
  val_mskdir: 'dataset/dataset_roi2/val_masks'

hyperparameters:
  loss_fn: 'binary_crossentropy'
  optimizer: 'adam' # sgd
  batch_size: 64
  num_epochs: 50
  lr: 0.001
  b1: 0.9
  b2: 0.999
  weight_decay: 0.0001
  scheduler: 
    type: 'step' # cosine, exponential
    gamma: 0.8
    step: 5
  n_gpus: 1

general:
  model_name: 'unet'
  pretrain: False
  n_classes: 1
  img_size: 224
